name: Deploy React App
on:
  push:
    branches: ['main']
    paths: ['frontend/**', '.github/workflows/deployment-frontend.yml']
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Pull Vercel Environment Information
        run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_PAT_TOKEN }}

      - name: Build Project Artifacts
        run: npx vercel build --prod --token=${{ secrets.VERCEL_PAT_TOKEN }}

      - name: Deploy Project Artifacts to vercel
        run: npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_PAT_TOKEN }}

      # - name: Build Production Bundle
      #   run: npm run build
      #   env:
      #     VITE_API_ROOTURL: { { $secrets.VITE_API_ROOTURL } }

      # - name: Deploy to Vercel
      #   uses: amondnet/vercel-action@v20
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Required
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Required
      #     working-directory: ./frontend
      #     vercel-args: '--prod' # Deploys directly to production
